use database;

CREATE TABLE IF NOT EXISTS Users (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS Purchases (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UserId INT UNSIGNED,
PurchaseDate Date,
Name varchar(50) NOT NULL,
Cost INT UNSIGNED,
FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE CASCADE
);