version: '3.0'

services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: database
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: secret
     volumes:
       - ./datafiles:/var/lib/mysql
       - ./init:/docker-entrypoint-initdb.d
     restart: always
     ports:
      - "1234:3306"