version: '3.0'

services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: database
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: secret
     volumes:
       - ./datafiles:/var/lib/mysql
       - ./init:/docker-entrypoint-initdb.d
     restart: always

   user:
     depends_on:
       - db
     image: maxide201/rtu_it_lab_lvl2:user_app
     build:
      context: .
     ports:
       - "8080:80"

   shop:
     depends_on:
       - db
     image: maxide201/rtu_it_lab_lvl2:shop_app
     build:
      context: .
     ports:
       - "8081:80"